#Backpack GUI title
title: "Backpack"

#All backpack items at the bottom.
backpack-items:
  upgrade:
    item: ENCHANTING_TABLE
    name: "Upgrade backpack"
    lore:
      - ""
      - "Upgrade capacity"
      - "Upgrade sell multi"
      - ""
  sell:
    item: EMERALD
    name: "Sell all for ${value}"
    lore:
      - ""
      - "Sell all your backpack!"
      - ""
  autosell:
    item: EMERALD_BLOCK
    name: "AutoSell"
    lore:
      - ""
      - "AutoSell your backpack"
      - ""

#Capacity upgrade button
capacity-upgrade:
  item: CHEST
  name: "Capacity Upgrade"
  lore:
    - ""
    - "Next Tier Tier {tier}"
    - "Cost: ${cost}"
    - "Capacity size: {capacity}"
    - ""


#GUI item once you have hit max upgrade
max-upgrade:
  item: BARRIER
  name: "You have maxed {upgrade} out!"
  lore:
    - ""
    - "No more upgrades!"
    - ""
#All the upgrades either storage or multi for sell
upgrades:
  storage:
    1:
      capacity: 25000
      cost: 0
    2:
      capacity: 45000
      cost: 10000000
    3:
      capacity: 100000
      cost: 30000000
  multi:
    1:
      multi: 1.0
      cost: 0
    2:
      multi: 2.0
      cost: 20000000
    3:
      multi: 3.5
      cost: 100000000